% default plot attributes
set(0,'DefaultAxesFontSize',    12, ...
      'DefaultLineLineWidth',   1, ...
      'DefaultAxesLineWidth',   1, ...
      'DefaultAxesFontWeight', 'normal', ...
      'DefaultFigureColor',     [1 1 1], ...
      'DefaultFigurePosition',  [10 700 800 350])
